robot:
  mass: 14.5
  base_link_name: "trunk"
  end_effectors_frame_names:
    - "FL_foot_fixed"
    - "FR_foot_fixed"
    - "RL_foot_fixed"
    - "RR_foot_fixed"
  dt: 0.001 # Estimation frequency
  initial_configuration: 
    [0.0, 0.0, 0.33, 0.0, 0.0, 0.0, 1.0, 0.1, 0.7, -1.45, 0.1, 0.7, -1.45, 0.1, 0.7, -1.45, 0.1, 0.7, -1.45]
  
  # Rotation and translation from base to IMU frame
  rot_base_to_imu:
    - [1.0, 0.0, 0.0]
    - [0.0, 1.0, 0.0]
    - [0.0, 0.0, 1.0]
  r_base_to_imu: [-0.01592, -0.06659, -0.00617]

